#!/bin/sh

if [ $# -ne 1 ]
then
    exit 1
fi

ouputs=''
next='\+0\+0'

for _ in $(xrandr | grep -P '(?<!dis)connected' | cut -d ' ' -f 1)
do
    tmp=$(xrandr | awk '/'${next}'/ {
            for (i=1;i<=NF;i++)
              if ($i ~ /'${next}'/)
                print $1, $i
            }')
    outputs="${outputs}$(echo $tmp | cut -d ' ' -f 1) "
    next=$(echo ${tmp} | cut -d ' ' -f 2 | cut -d 'x' -f 1)
    next="\+${next}\+"
done

wk=$(i3-msg -t get_workspaces |
     jq 'map(select(.focused)) | .[].name' |
     tr -d \")
output=$(echo ${outputs} | awk "{print \$${1}}")

i3-msg "workspace ${wk}; move workspace to output ${output}; workspace ${wk}"
