#!/bin/sh

if [ $# -ne 1 ]
then
    exit 1
fi

ouputs=''
next='\+0\+0'

while true
do
    tmp=$(xrandr | awk '/'${next}'/ {
            for (i=1;i<=NF;i++)
              if ($i ~ /'${next}'/)
                print $1, $i
            }')
    if [ -z "${tmp}" ]
    then
      break
    fi

    outputs="${outputs}$(echo $tmp | cut -d ' ' -f 1) "

    length=$(echo ${tmp} | awk '{print $2}' | cut -d x -f 1)
    current=$(echo ${tmp} | awk '{print $2}' | cut -d + -f 2)
    next="\+$(( ${length} + ${current} ))\+0"
done

wk=$(i3-msg -t get_workspaces |
     jq 'map(select(.focused)) | .[].name' |
     tr -d \")
output=$(echo ${outputs} | awk "{print \$${1}}")

i3-msg "workspace ${wk}; move workspace to output ${output}; workspace ${wk}"
